name: Markdown CI

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.markdown'
  push:
    branches: [main, master]
    paths:
      - '**/*.md'
      - '**/*.markdown'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    name: Lint Markdown files
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2
        
      - name: Run Markdown linting
        run: markdownlint-cli2 "**/*.{md,markdown}" "#node_modules"

  spell-check:
    runs-on: ubuntu-latest
    name: Spell check Markdown files
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install cSpell
        run: npm install -g cspell
        
      - name: Run spell check
        run: cspell "**/*.{md,markdown}" --no-progress --show-context

  prettier-check:
    runs-on: ubuntu-latest
    name: Check code formatting with Prettier
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Prettier
        run: npm install -g prettier
        
      - name: Check formatting
        run: prettier --check "**/*.{js,jsx,ts,tsx,json,css,scss,html,md,markdown,yml,yaml}"
